name: vmusic
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  on_audio_query: ^2.9.0
  transparent_image: ^2.0.1
  just_audio: ^0.9.37
  permission_handler: ^11.3.1
  audio_video_progress_bar: ^2.0.3
  audio_service: ^0.18.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0


flutter:
  uses-material-design: true

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/font/Vazirmatn-VariableFont_wght.ttf